#
# dreigada bash settings
#

DOTFILES_DEFAULT="$HOME/.$(whoami)rc"
DOTFILES=${DOTFILES-$DOTFILES_DEFAULT}

if [ -d "$DOTFILES" ]; then
	# Theme
	source $DOTFILES/bash/themes/agnoster/agnoster.bash

	# Customize to your needs...
	for config_file in "$(ls $DOTFILES/shells/sources/*)"; do source $config_file; done
fi

if [[ -s "$HOME/.nodenv/bin/nodenv" ]]; then
  eval "$($HOME/.nodenv/bin/nodenv init - --no-rehash zsh)"
fi

if [[ -s "$HOME/.rbenv/bin/rbenv" ]]; then
	eval "$($HOME/.rbenv/bin/rbenv init - --no-rehash zsh)"
fi

#sublime text
export PATH=$PATH:/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/

#Psql app
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin


#Docker
source ~/.docker_aliases

#Git
source ~/.git-completion.bash
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
